In [1]:
#import what the exercises call for
import numpy as np

In [2]:
#this is the original numpy array given to us in the exercise
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [3]:
mask = a[a<0]
mask

array([-2, -1, -6, -7])

In [4]:
a[a<0]

array([-2, -1, -6, -7])

In [5]:
len(a[a<0])

4

In [6]:
len(mask)

4

In [8]:
pos_num = a[a>0]
pos_num

array([ 4, 10, 12, 23,  3])

In [9]:
pos_num

array([ 4, 10, 12, 23,  3])

In [10]:
pos_and_even = pos_num[pos_num %2 ==0]

In [11]:
pos_and_even

array([ 4, 10, 12])

In [12]:
len(pos_and_even)

3

In [13]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [15]:
c= a+3
c

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [16]:
sum_3 = a[(a+3) >0]

len(sum_3)

10

In [17]:
squared = a **2

In [18]:
squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [20]:
mean = squared.mean()
mean

74.0

In [22]:
standev = squared.std()
standev

144.0243035046516

In [23]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [24]:
a.mean()

3.0

In [25]:
center_a = a - a.mean()
center_a

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [ ]:
z_scored = centered_a /a.std()